name: CD
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull nazmialtun/testokur-identity:latest
            docker stop testokur-identity && docker rm testokur-identity --force
            docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined  -d \
            --env-file /home/env/identity.env \
            -v /home/cert:/app/cert \
            --name testokur-identity \
            --restart=unless-stopped \
            --network=testokur \
            --network-alias=identity \
            nazmialtun/testokur-identity:latest
            echo Y | docker system prune