name: CI
on:
  push:
    tags-ignore:
      - 'v*'
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Disable DotNet First Usage Messsage
        run: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"
      - name: Start postgres 
        run: |
          docker run -d -e POSTGRES_PASSWORD=password -e POSTGRES_USER=user -e POSTGRES_DB=identity -p 6433:5432 nazmialtun/postgres-tr
      - name: Install sonar-scanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Begin sonar scanning
        run: dotnet-sonarscanner begin /k:testokur_testokur-identity /n:testokur-identity /o:testokur 
          /d:sonar.host.url=https://sonarcloud.io /version:${{ github.run_number }} /d:sonar.login=${{secrets.SONAR_TOKEN}}
          /d:sonar.cs.opencover.reportsPaths=coverage/*.xml
      - name: Build
        run: dotnet build -c Release ${SOLUTION_PATH}
      - name: Run Tests
        run: dotnet test --no-restore --no-build -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=../../coverage/integration.xml
      - name: End sonar scanning
        run: dotnet-sonarscanner end /d:sonar.login=${{secrets.SONAR_TOKEN}}
  docker:
    needs: [tests]
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          docker build -t nazmialtun/testokur-identity:${{ github.run_number }} -t nazmialtun/testokur-identity:latest -f src/TestOkur.Identity/Dockerfile .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker Images to Registry
        run: |
          docker push nazmialtun/testokur-identity:latest
          docker push nazmialtun/testokur-identity:${{ github.run_number }}